// flow-typed signature: e9c5c656aea95b2cd6c94f952873881b
// flow-typed version: <<STUB>>/bankai_v^8.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bankai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bankai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bankai/bin' {
  declare module.exports: any;
}

declare module 'bankai/example' {
  declare module.exports: any;
}

declare module 'bankai/lib/electron' {
  declare module.exports: any;
}

declare module 'bankai/lib/gzip-maybe' {
  declare module.exports: any;
}

declare module 'bankai/lib/html-minify-stream' {
  declare module.exports: any;
}

declare module 'bankai/lib/sse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bankai/bin.js' {
  declare module.exports: $Exports<'bankai/bin'>;
}
declare module 'bankai/example.js' {
  declare module.exports: $Exports<'bankai/example'>;
}
declare module 'bankai/index' {
  declare module.exports: $Exports<'bankai'>;
}
declare module 'bankai/index.js' {
  declare module.exports: $Exports<'bankai'>;
}
declare module 'bankai/lib/electron.js' {
  declare module.exports: $Exports<'bankai/lib/electron'>;
}
declare module 'bankai/lib/gzip-maybe.js' {
  declare module.exports: $Exports<'bankai/lib/gzip-maybe'>;
}
declare module 'bankai/lib/html-minify-stream.js' {
  declare module.exports: $Exports<'bankai/lib/html-minify-stream'>;
}
declare module 'bankai/lib/sse.js' {
  declare module.exports: $Exports<'bankai/lib/sse'>;
}
