// flow-typed signature: 91e323ed41975bbe959dd4676fb5d23d
// flow-typed version: <<STUB>>/sheetify_v^6.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sheetify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sheetify' {
  declare module.exports: (string[], ...string[]) => string;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sheetify/browser' {
  declare module.exports: any;
}

declare module 'sheetify/example/index' {
  declare module.exports: any;
}

declare module 'sheetify/insert' {
  declare module.exports: any;
}

declare module 'sheetify/test/fixtures/import-broken-source' {
  declare module.exports: any;
}

declare module 'sheetify/test/fixtures/import-source' {
  declare module.exports: any;
}

declare module 'sheetify/test/fixtures/plugins-source' {
  declare module.exports: any;
}

declare module 'sheetify/test/fixtures/prefix-import-source' {
  declare module.exports: any;
}

declare module 'sheetify/test/fixtures/prefix-inline-source' {
  declare module.exports: any;
}

declare module 'sheetify/test/import' {
  declare module.exports: any;
}

declare module 'sheetify/test/index' {
  declare module.exports: any;
}

declare module 'sheetify/test/json' {
  declare module.exports: any;
}

declare module 'sheetify/test/noparse' {
  declare module.exports: any;
}

declare module 'sheetify/test/plugins' {
  declare module.exports: any;
}

declare module 'sheetify/test/prefix' {
  declare module.exports: any;
}

declare module 'sheetify/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sheetify/browser.js' {
  declare module.exports: $Exports<'sheetify/browser'>;
}
declare module 'sheetify/example/index.js' {
  declare module.exports: $Exports<'sheetify/example/index'>;
}
declare module 'sheetify/index' {
  declare module.exports: $Exports<'sheetify'>;
}
declare module 'sheetify/index.js' {
  declare module.exports: $Exports<'sheetify'>;
}
declare module 'sheetify/insert.js' {
  declare module.exports: $Exports<'sheetify/insert'>;
}
declare module 'sheetify/test/fixtures/import-broken-source.js' {
  declare module.exports: $Exports<'sheetify/test/fixtures/import-broken-source'>;
}
declare module 'sheetify/test/fixtures/import-source.js' {
  declare module.exports: $Exports<'sheetify/test/fixtures/import-source'>;
}
declare module 'sheetify/test/fixtures/plugins-source.js' {
  declare module.exports: $Exports<'sheetify/test/fixtures/plugins-source'>;
}
declare module 'sheetify/test/fixtures/prefix-import-source.js' {
  declare module.exports: $Exports<'sheetify/test/fixtures/prefix-import-source'>;
}
declare module 'sheetify/test/fixtures/prefix-inline-source.js' {
  declare module.exports: $Exports<'sheetify/test/fixtures/prefix-inline-source'>;
}
declare module 'sheetify/test/import.js' {
  declare module.exports: $Exports<'sheetify/test/import'>;
}
declare module 'sheetify/test/index.js' {
  declare module.exports: $Exports<'sheetify/test/index'>;
}
declare module 'sheetify/test/json.js' {
  declare module.exports: $Exports<'sheetify/test/json'>;
}
declare module 'sheetify/test/noparse.js' {
  declare module.exports: $Exports<'sheetify/test/noparse'>;
}
declare module 'sheetify/test/plugins.js' {
  declare module.exports: $Exports<'sheetify/test/plugins'>;
}
declare module 'sheetify/test/prefix.js' {
  declare module.exports: $Exports<'sheetify/test/prefix'>;
}
declare module 'sheetify/transform.js' {
  declare module.exports: $Exports<'sheetify/transform'>;
}
